use super::*;

// Freecam hook 1: Main camera logic (matches CT hook at DARKSOULS.exe+B00AD4)
#[cfg(all(target_os = "windows", target_arch = "x86"))]
#[unsafe(naked)]
pub(super) unsafe extern "C" fn freecam_hook_1() {
    std::arch::naked_asm!(
        // Increment hook entry counter
        "inc dword ptr [{hook_entry}]",

        // Original instruction 1: mov [esp+0x24], eax
        "mov dword ptr [esp+0x24], eax",

        // Save registers (match CT exactly)
        "push ebp",
        "push esi",
        "push edi",
        "push ecx",
        "push edx",
        "sub esp, 0xC",

        // Set in-hook flag
        "mov byte ptr [{in_hook}], 1",
        // Release variant note: game-native button bits differ from CT mapping on this build
        // (observed L3+X false positives). Keep mode cycling in Rust XInput path only.
        "mov byte ptr [{l3r3_held}], 0",
        "mov dword ptr [{debug_input_8}], 0",
        "mov dword ptr [{debug_input_c}], 0",
        "afterModeCycle:",
        "mov ecx, dword ptr [{mode}]",

        // Get camera manager (read pointer then dereference)
        "mov esi, dword ptr [{cam_mgr_ptr}]",
        "test esi, esi",
        "je freeCamFinish",
        "mov esi, dword ptr [esi]",
        "test esi, esi",
        "je freeCamFinish",
        // Get camera object
        "mov eax, dword ptr [esi+0x6F8]",
        "test eax, eax",
        "je freeCamFinish",
        // Save camera object address for debug
        "push eax",
        "mov dword ptr [{debug_cam_obj}], eax",
        "pop eax",
        // Capture camera transform buffer pointers for diagnostics
        "mov ecx, dword ptr [eax+0x18]",
        "mov dword ptr [{debug_buf_18}], ecx",
        "mov ecx, dword ptr [eax+0x30]",
        "mov dword ptr [{debug_buf_30}], ecx",
        "mov ecx, dword ptr [eax+0x254]",
        "mov dword ptr [{debug_buf_254}], ecx",
        // Write mode
        "mov ecx, dword ptr [{mode}]",
        "cmp ecx, 0",
        "je modeWrite",
        "cmp byte ptr [{force_mode2_active_only}], 1",
        "jne modeWrite",
        "mov ecx, 2",
        "modeWrite:",
        "mov dword ptr [eax+0x24C], ecx",
        // Jump based on mode
        "cmp ecx, 1",
        "je freeCamMode1",
        "cmp ecx, 2",
        "je freeCamMode2",
        "cmp ecx, 3",
        "je freeCamMode3",
        // Default: mode 0
        "jmp freeCamMode0",

        // Mode 0: Copy current camera to storage (initialize)
        "freeCamMode0:",
        "mov edi, dword ptr [eax+0x254]",
        "mov esi, dword ptr [eax+0x18]",

        // Release variant: +0x18 can be NULL. Fall back to +0x30 (render buffer).
        "test esi, esi",
        "jne mode0_have_src",
        "mov esi, dword ptr [eax+0x30]",
        "test esi, esi",
        "je freeCamFinish",
        "mode0_have_src:",

        // If +0x254 is unavailable, use our static storage buffer as persistent freecam state.
        "test edi, edi",
        "jne mode0_do_copy",
        "lea edi, [{storage_buf}]",

        "mode0_do_copy:",
        "movups xmm0, [esi+0x10]",
        "movups [edi+0x10], xmm0",
        "movups xmm0, [esi+0x20]",
        "movups [edi+0x20], xmm0",
        "movups xmm0, [esi+0x30]",
        "movups [edi+0x30], xmm0",
        "movups xmm0, [esi+0x40]",
        "movups [edi+0x40], xmm0",
        "mov byte ptr [ebx+0x58], 0",
        "mov byte ptr [ebx+0x59], 0",
        "jmp freeCamFinish",

        // Mode 1: Check freeze state, else jump to update motion (matches CE)
        "freeCamMode1:",
        "mov ebp, [edx+4]",
        "mov ebp, [ebp+0x28]",
        "mov ebp, [ebp+0xC]",
        "shr ebp, 3",
        "test ebp, 1",
        "je frozen",
        "jmp freeCamMode2",
        "frozen:",
        "mov byte ptr [ebx+0x58], 1",
        "mov byte ptr [ebx+0x59], 1",
        "jmp freeCamUpdateMotion",
        // Mode 2: Always jump to update motion
        "freeCamMode2:",
        "mov byte ptr [ebx+0x58], 0",
        "mov byte ptr [ebx+0x59], 0",
        "jmp freeCamUpdateMotion",
        // Shared update motion logic for mode 1 (not frozen) and mode 2
        "freeCamUpdateMotion:",
        "mov byte ptr [ebx+0x44], 1",
        "mov esi, dword ptr [eax+0x30]",
        "test esi, esi",
        "je freeCamFinish",
        "mov dword ptr [{hook_last_src}], esi",
        "mov edi, dword ptr [eax+0x254]",
        // +0x254 can be null on some PTDE variants. Keep an independent storage source.
        "test edi, edi",
        "jne update_dst_ready",
        "lea edi, [{storage_buf}]",
        "update_dst_ready:",
        "mov dword ptr [{hook_last_dst}], edi",
        "movups xmm0, [edi+0x10]",
        "movups [esi+0x10], xmm0",
        "movups xmm0, [edi+0x20]",
        "movups [esi+0x20], xmm0",
        "movups xmm0, [edi+0x30]",
        "movups [esi+0x30], xmm0",
        "movups xmm0, [edi+0x40]",
        "movups [esi+0x40], xmm0",
        "mov ebp, [{motion_func}]",
        "mov dword ptr [{debug_func_addr}], ebp",
        "cmp byte ptr [{motion_call_safe}], 1",
        "jne skipMotionCall",
        "push edx",
        "push edi",
        "inc dword ptr [{debug_called}]",
        "call ebp",
        "skipMotionCall:",

        // Enforce movement directly on live render/source buffers.
        "fld dword ptr [esi+0x40]",
        "fadd dword ptr [{move_dx}]",
        "fstp dword ptr [esi+0x40]",
        "fld dword ptr [esi+0x44]",
        "fadd dword ptr [{move_dy}]",
        "fstp dword ptr [esi+0x44]",
        "fld dword ptr [esi+0x48]",
        "fadd dword ptr [{move_dz}]",
        "fstp dword ptr [esi+0x48]",
        "fld dword ptr [esi+0x1C]",
        "fadd dword ptr [{move_dx}]",
        "fstp dword ptr [esi+0x1C]",
        "fld dword ptr [esi+0x2C]",
        "fadd dword ptr [{move_dy}]",
        "fstp dword ptr [esi+0x2C]",
        "fld dword ptr [esi+0x3C]",
        "fadd dword ptr [{move_dz}]",
        "fstp dword ptr [esi+0x3C]",
        "fld dword ptr [esi+0x30]",
        "fadd dword ptr [{move_dx}]",
        "fstp dword ptr [esi+0x30]",
        "fld dword ptr [esi+0x34]",
        "fadd dword ptr [{move_dy}]",
        "fstp dword ptr [esi+0x34]",
        "fld dword ptr [esi+0x38]",
        "fadd dword ptr [{move_dz}]",
        "fstp dword ptr [esi+0x38]",
        "cmp edi, esi",
        "je postMoveDone",
        "fld dword ptr [edi+0x40]",
        "fadd dword ptr [{move_dx}]",
        "fstp dword ptr [edi+0x40]",
        "fld dword ptr [edi+0x44]",
        "fadd dword ptr [{move_dy}]",
        "fstp dword ptr [edi+0x44]",
        "fld dword ptr [edi+0x48]",
        "fadd dword ptr [{move_dz}]",
        "fstp dword ptr [edi+0x48]",
        "fld dword ptr [edi+0x1C]",
        "fadd dword ptr [{move_dx}]",
        "fstp dword ptr [edi+0x1C]",
        "fld dword ptr [edi+0x2C]",
        "fadd dword ptr [{move_dy}]",
        "fstp dword ptr [edi+0x2C]",
        "fld dword ptr [edi+0x3C]",
        "fadd dword ptr [{move_dz}]",
        "fstp dword ptr [edi+0x3C]",
        "postMoveDone:",

        // Hook-side telemetry only. All movement writes are done in Rust-side validated code
        // to avoid crashes when pause/emote/menu states change camera pointer lifetimes.
        "inc dword ptr [{hook_apply_count}]",
        "fld dword ptr [{move_dx}]",
        "fstp dword ptr [{hook_move_dx}]",
        "fld dword ptr [{move_dy}]",
        "fstp dword ptr [{hook_move_dy}]",
        "fld dword ptr [{move_dz}]",
        "fstp dword ptr [{hook_move_dz}]",
        "fld dword ptr [esi+0x40]",
        "fstp dword ptr [{hook_post_40}]",
        "fld dword ptr [esi+0x44]",
        "fstp dword ptr [{hook_post_44}]",
        "fld dword ptr [esi+0x48]",
        "fstp dword ptr [{hook_post_48}]",
        "jmp freeCamFinish",

        // Mode 3: Copy stored back to current
        "freeCamMode3:",
        "mov esi, dword ptr [eax+0x30]",
        "mov edi, dword ptr [eax+0x254]",

        // Release variant: +0x254 can be NULL. Fall back to static storage if needed.
        "test esi, esi",
        "je freeCamFinish",
        "test edi, edi",
        "jne mode3_do_copy",
        "lea edi, [{storage_buf}]",
        "mode3_do_copy:",
        "movups xmm0, [edi+0x10]",
        "movups [esi+0x10], xmm0",
        "movups xmm0, [edi+0x20]",
        "movups [esi+0x20], xmm0",
        "movups xmm0, [edi+0x30]",
        "movups [esi+0x30], xmm0",
        "movups xmm0, [edi+0x40]",
        "movups [esi+0x40], xmm0",
        "mov byte ptr [ebx+0x58], 0",
        "mov byte ptr [ebx+0x59], 0",
        "jmp freeCamFinish",

        "freeCamFinish:",
        "add esp, 0xC",
        "pop edx",
        "pop ecx",
        "pop edi",
        "pop esi",
        "pop ebp",
        "mov byte ptr [{in_hook}], 0",

        // Original instruction 2
        "mov eax, dword ptr [ebx+0x44]",

        // Return
        "mov ecx, [{inject1}]",
        "add ecx, 7",
        "jmp ecx",

        hook_entry = sym FREECAM_DEBUG_HOOK_ENTRY,
        inject1 = sym FREECAM_INJECT_ADDR_1,
        motion_call_safe = sym FREECAM_MOTION_CALL_SAFE,
        motion_func = sym FREECAM_MOTION_FUNC,
        move_dx = sym FREECAM_MOVE_DX,
        move_dy = sym FREECAM_MOVE_DY,
        move_dz = sym FREECAM_MOVE_DZ,
        force_mode2_active_only = sym FREECAM_FORCE_MODE2_ACTIVE_ONLY,
        in_hook = sym FREECAM_IN_HOOK,
        l3r3_held = sym FREECAM_L3R3_HELD,
        mode = sym FREECAM_MODE,
        cam_mgr_ptr = sym FREECAM_CAM_MGR_PTR,
        debug_cam_obj = sym FREECAM_DEBUG_CAM_OBJ,
        debug_buf_18 = sym FREECAM_DEBUG_BUF_18,
        debug_buf_30 = sym FREECAM_DEBUG_BUF_30,
        debug_buf_254 = sym FREECAM_DEBUG_BUF_254,
        hook_apply_count = sym FREECAM_DEBUG_HOOK_APPLY_COUNT,
        hook_last_dst = sym FREECAM_DEBUG_HOOK_LAST_DST,
        hook_last_src = sym FREECAM_DEBUG_HOOK_LAST_SRC,
        hook_move_dx = sym FREECAM_DEBUG_HOOK_MOVE_DX,
        hook_move_dy = sym FREECAM_DEBUG_HOOK_MOVE_DY,
        hook_move_dz = sym FREECAM_DEBUG_HOOK_MOVE_DZ,
        hook_post_40 = sym FREECAM_DEBUG_HOOK_POST_40,
        hook_post_44 = sym FREECAM_DEBUG_HOOK_POST_44,
        hook_post_48 = sym FREECAM_DEBUG_HOOK_POST_48,
        debug_func_addr = sym FREECAM_DEBUG_FUNC_ADDR,
        debug_called = sym FREECAM_DEBUG_CALLED_FUNC,
        debug_input_8 = sym FREECAM_DEBUG_INPUT_RAW_8,
        debug_input_c = sym FREECAM_DEBUG_INPUT_RAW_C,
        storage_buf = sym FREECAM_STORAGE_BUFFER,
    );
}

// Freecam hook 2: Skip camera constraint check when in freecam (matches CT hook at DARKSOULS.exe+BFB431)
#[cfg(all(target_os = "windows", target_arch = "x86"))]
#[unsafe(naked)]
pub(super) unsafe extern "C" fn freecam_hook_2() {
    std::arch::naked_asm!(
        "inc dword ptr [{hook2_entry}]",
        "cmp byte ptr [{in_hook}], 1",
        "je skip_original",
        "do_original:",
        "inc dword ptr [{hook2_orig}]",
        // Original instructions
        "shr edx, 0x14",
        "test dl, 1",
        "jmp ret_hook2",
        "skip_original:",
        "inc dword ptr [{hook2_skip}]",
        // Jump to the original conditional-branch target when bypassing this check.
        "mov ecx, [{hook2_skip_addr}]",
        "test ecx, ecx",
        "jne jump_skip_target",
        "ret_hook2:",
        // Return to original code (addr + 6)
        "mov ecx, [{inject2}]",
        "add ecx, 6",
        "jmp ecx",
        "jump_skip_target:",
        "jmp ecx",
        in_hook = sym FREECAM_IN_HOOK,
        inject2 = sym FREECAM_INJECT_ADDR_2,
        hook2_skip_addr = sym FREECAM_HOOK2_SKIP_ADDR,
        hook2_entry = sym FREECAM_DEBUG_HOOK2_ENTRY_COUNT,
        hook2_skip = sym FREECAM_DEBUG_HOOK2_SKIP_COUNT,
        hook2_orig = sym FREECAM_DEBUG_HOOK2_ORIG_COUNT,
    );
}
