use super::*;

// XInput hook: Intercepts XInputGetState to inject button inputs
#[cfg(all(target_os = "windows", target_arch = "x86"))]
#[unsafe(naked)]
pub(super) unsafe extern "system" fn xinput_hook() {
    std::arch::naked_asm!(
        // This is a stdcall function with signature: DWORD XInputGetState(DWORD dwUserIndex, XINPUT_STATE *pState)
        // Parameters: [esp+4] = user_index, [esp+8] = state pointer
        // We must preserve all registers and return with ret 8

        "pushad",
        "cmp byte ptr [{hook_enabled}], 0",
        "je unhook_in_progress",
        "inc dword ptr [{call_count}]",
        "mov eax, dword ptr [esp+36]",
        "mov dword ptr [{last_user_index}], eax",
        "mov eax, dword ptr [{trampoline}]",
        "test eax, eax",
        "jz error_no_trampoline",
        "mov ecx, dword ptr [esp+40]",
        "push ecx",
        "mov ecx, dword ptr [esp+40]",
        "push ecx",
        "call eax",
        "mov dword ptr [esp+28], eax",
        "test eax, eax",
        "jnz skip_track",
        "mov ecx, dword ptr [esp+40]",
        "test ecx, ecx",
        "jz skip_track",
        "movzx edx, word ptr [ecx+4]",
        "mov word ptr [{current_buttons}], dx",
        "movzx edx, byte ptr [ecx+6]",
        "mov byte ptr [{current_left_trigger}], dl",
        "movzx edx, byte ptr [ecx+7]",
        "mov byte ptr [{current_right_trigger}], dl",
        "movsx edx, word ptr [ecx+8]",
        "mov word ptr [{current_thumb_lx}], dx",
        "movsx edx, word ptr [ecx+10]",
        "mov word ptr [{current_thumb_ly}], dx",
        "movsx edx, word ptr [ecx+12]",
        "mov word ptr [{current_thumb_rx}], dx",
        "movsx edx, word ptr [ecx+14]",
        "mov word ptr [{current_thumb_ry}], dx",
        "skip_track:",
        "test eax, eax",
        "jnz skip_inject",
        "cmp byte ptr [{inject_enabled}], 0",
        "je skip_inject",
        "mov ecx, dword ptr [esp+40]",
        "test ecx, ecx",
        "jz skip_inject",
        "movzx eax, word ptr [{inject_buttons}]",
        "test ax, ax",
        "jz skip_buttons",
        "or word ptr [ecx+4], ax",
        "skip_buttons:",
        "movzx eax, byte ptr [{inject_left_trigger}]",
        "test al, al",
        "jz skip_left_trigger",
        "mov byte ptr [ecx+6], al",
        "skip_left_trigger:",
        "movzx eax, byte ptr [{inject_right_trigger}]",
        "test al, al",
        "jz skip_right_trigger",
        "mov byte ptr [ecx+7], al",
        "skip_right_trigger:",
        "movsx eax, word ptr [{inject_thumb_lx}]",
        "test ax, ax",
        "jz skip_thumb_lx",
        "mov word ptr [ecx+8], ax",
        "skip_thumb_lx:",
        "movsx eax, word ptr [{inject_thumb_ly}]",
        "test ax, ax",
        "jz skip_thumb_ly",
        "mov word ptr [ecx+10], ax",
        "skip_thumb_ly:",
        "movsx eax, word ptr [{inject_thumb_rx}]",
        "test ax, ax",
        "jz skip_thumb_rx",
        "mov word ptr [ecx+12], ax",
        "skip_thumb_rx:",
        "movsx eax, word ptr [{inject_thumb_ry}]",
        "test ax, ax",
        "jz skip_thumb_ry",
        "mov word ptr [ecx+14], ax",
        "skip_thumb_ry:",
        "skip_inject:",
        "popad",
        "ret 8",
        "unhook_in_progress:",
        "popad",
        "mov eax, 0xFFFFFFFF",
        "ret 8",
        "error_no_trampoline:",
        "popad",
        "mov eax, 0xFFFFFFFF",
        "ret 8",
        hook_enabled = sym XINPUT_HOOK_ENABLED,
        trampoline = sym XINPUT_TRAMPOLINE,
        inject_enabled = sym XINPUT_INJECT_ENABLED,
        inject_buttons = sym XINPUT_INJECT_BUTTONS,
        current_buttons = sym XINPUT_CURRENT_BUTTONS,
        call_count = sym XINPUT_CALL_COUNT,
        last_user_index = sym XINPUT_LAST_USER_INDEX,
        inject_left_trigger = sym XINPUT_INJECT_LEFT_TRIGGER,
        inject_right_trigger = sym XINPUT_INJECT_RIGHT_TRIGGER,
        inject_thumb_lx = sym XINPUT_INJECT_THUMB_LX,
        inject_thumb_ly = sym XINPUT_INJECT_THUMB_LY,
        inject_thumb_rx = sym XINPUT_INJECT_THUMB_RX,
        inject_thumb_ry = sym XINPUT_INJECT_THUMB_RY,
        current_left_trigger = sym XINPUT_CURRENT_LEFT_TRIGGER,
        current_right_trigger = sym XINPUT_CURRENT_RIGHT_TRIGGER,
        current_thumb_lx = sym XINPUT_CURRENT_THUMB_LX,
        current_thumb_ly = sym XINPUT_CURRENT_THUMB_LY,
        current_thumb_rx = sym XINPUT_CURRENT_THUMB_RX,
        current_thumb_ry = sym XINPUT_CURRENT_THUMB_RY,
    );
}
